apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-prometheus
  namespace: gv-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gv-prometheus
  template:
    metadata:
      labels:
        app: gv-prometheus
    spec:
      serviceAccountName: gv-prometheus
      containers:
        - name: gv-prometheus
          image: prom/prometheus:v2.54.1
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: gv-prometheus-config
              mountPath: /etc/prometheus
            - name: gv-prometheus-data
              mountPath: /prometheus
      volumes:
        - name: gv-prometheus-config
          configMap:
            name: gv-prometheus-config
        - name: gv-prometheus-data
          emptyDir: {}
