apiVersion: v1
kind: Service
metadata:
  name: gv-prometheus
  namespace: gv-monitoring
spec:
  selector:
    app: gv-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP