apiVersion: v1
kind: Service
metadata:
  name: gv-prometheus
  namespace: gv-monitoring
spec:
  type: ClusterIP
  selector:
    app: gv-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
