apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-frontend
  namespace: gv-webstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gv-frontend
  template:
    metadata:
      labels:
        app: gv-frontend
    spec:
      containers:
        - name: gv-frontend
          image: frontend-apache
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
