apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-grafana
  namespace: gv-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gv-grafana
  template:
    metadata:
      labels:
        app: gv-grafana
    spec:
      containers:
        - name: gv-grafana
          image: grafana/grafana:10.4.5
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: gv-grafana-admin
                  key: GF_SECURITY_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gv-grafana-admin
                  key: GF_SECURITY_ADMIN_PASSWORD
          volumeMounts:
            - name: gv-grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: gv-grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: gv-grafana-dashboard
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: gv-grafana-datasource
          configMap:
            name: gv-grafana-datasource
        - name: gv-grafana-dashboards
          configMap:
            name: gv-grafana-dashboards
        - name: gv-grafana-dashboard
          configMap:
            name: gv-grafana-dashboard
