apiVersion: v1
kind: Service
metadata:
  name: gv-grafana
  namespace: gv-monitoring
spec:
  type: ClusterIP
  selector:
    app: gv-grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
