apiVersion: v1
kind: Service
metadata:
  name: gv-api
  namespace: gv-webstack
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app: gv-api
  ports:
    - port: 8000
      targetPort: 8000
